# Generated by Django 3.2.8 on 2022-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PKOB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='bantuan',
            field=models.CharField(choices=[('BBP', 'Bantuan Baik Pulih'), ('BRB', 'Bantuan Rumah Baru'), ('BB', 'Bantuan Bulanan'), ('BBM', 'Bantuan Bekalan Makanan')], default='BBP', max_length=5),
        ),
    ]
