# Generated by Django 3.2.8 on 2022-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PKOB', '0002_alter_victim_bantuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='bantuan',
            field=models.CharField(max_length=50, verbose_name='BANTUAN'),
        ),
    ]
