# Generated by Django 3.2.8 on 2022-01-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_PKOB', '0004_receive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receive',
        ),
    ]
