# Generated by Django 3.2.8 on 2022-01-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PKOB', '0005_delete_receive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mukim', models.CharField(max_length=50, verbose_name='MUKIM')),
                ('name', models.CharField(max_length=50, verbose_name='NAMA')),
                ('phone_no', models.CharField(max_length=11, verbose_name='NO TELEFON')),
                ('ic_no', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='NO IC')),
                ('no_rumah', models.CharField(max_length=50, verbose_name='NO RUMAH')),
                ('jalan_lrg', models.CharField(max_length=50, verbose_name='JALAN/LRG')),
                ('kg_tmn', models.CharField(max_length=50, verbose_name='KG/TMN')),
                ('kerja', models.CharField(max_length=50, verbose_name='PEKERJAAN')),
                ('tanggungan', models.CharField(max_length=50, verbose_name='TANGGUNGAN')),
                ('sebab', models.CharField(max_length=50, verbose_name='SEBAB MOHON')),
                ('pendapatan', models.CharField(max_length=50, verbose_name='PENDAPATAN')),
                ('bantuan', models.CharField(max_length=50, verbose_name='BANTUAN')),
            ],
        ),
    ]
